name: expense_tracker
description: A simple expense tracker app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  vector_math: ^2.2.0
  characters: ^1.4.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.1